# based on r&d these are the content present on a website in that case the website is invalid.

bad_websites = [
    "looks like this domain isn't connected to a website",
    "this domain is not connected to a website",
    "the request could not be satisfied",
    "the page you requested does not exist",
    "the page you requested doesn't exist",
    "the page you requested was not found",
    "please contact your hosting provider",
    "we looked everywhere for this page!",
    "the requested url / was not found",
    "the site is not yet installed",
    "domain is available for sale",
    "this site cant be reached",
    "contact the site owner",
    "no web page was found",
    "domain not available",
    "please check the url",
    "page can't be found",
    "domain not claimed",
    "website not found",
    "website expired",
    "domain for sale",
    "buy this domain",
    "get this domain",
    "site not found",
    "404 not found",
    "is available on godaddy auctions",
    "website under construction",
    "website is under construction",
    "if you are the owner of this website",
    "please contact your hosting provider",
    "site not published",
    "if you're the site owner log in to launch this site",
    "if you are a visitor check back soon",
    "this site is currently unavailable",
    "buy this domain",
    "this domain may be for sale",
    "click here to inquire about this domain",
    "this page is under construction",
    "this domain is successfully pointed at wp engine but is not configured for an account on our platform",
    "If you are the owner of this website please contact your hosting provider"
]
